basePath: /
definitions:
  api.AddMenuAuthorityInfo:
    properties:
      authorityID:
        type: string
      menus:
        items:
          $ref: '#/definitions/model.BaseMenu'
        type: array
    type: object
  api.AuthAndPathIn:
    properties:
      apiIds:
        items:
          type: integer
        type: array
      authorityId:
        type: string
    type: object
  api.AuthorityIDInfo:
    properties:
      authorityID:
        type: string
    type: object
  api.ChangePasswordStruct:
    properties:
      newPassword:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  api.CreateAPIParams:
    properties:
      description:
        type: string
      path:
        type: string
    type: object
  api.CreateAuthorityPatams:
    properties:
      authorityId:
        type: string
      authorityName:
        type: string
    type: object
  api.DeleteAuthorityPatams:
    properties:
      authorityId:
        type: integer
    type: object
  api.GetAuthorityID:
    properties:
      authorityId:
        type: string
    type: object
  api.GetByID:
    properties:
      id:
        type: number
    type: object
  api.IDInfo:
    properties:
      id:
        type: number
    type: object
  api.RegistAndLoginStuct:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api.SetUserAuth:
    properties:
      authorityId:
        type: string
      uuid:
        type: string
    type: object
  api.response:
    properties:
      data:
        type: object
      msg:
        type: string
      success:
        type: boolean
    type: object
  model.API:
    properties:
      description:
        type: string
      group:
        type: string
      path:
        type: string
    type: object
  model.BaseMenu:
    properties:
      children:
        items:
          $ref: '#/definitions/model.BaseMenu'
        type: array
      component:
        type: string
      hidden:
        type: boolean
      icon:
        type: string
      name:
        type: string
      nickName:
        type: string
      parentId:
        type: string
      path:
        type: string
      title:
        type: string
    type: object
  modelinterface.PageInfo:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample Server pets
  license: {}
  title: Swagger Example API
  version: 0.0.1
paths:
  /api/createApi:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建api
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.CreateAPIParams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 创建基础api
      tags:
      - API
  /api/deleteApi:
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除api
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.API'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 删除指定api
      tags:
      - API
  /api/getAllApis:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 获取所有的Api 不分页
      tags:
      - API
  /api/getApiById:
    post:
      consumes:
      - application/json
      parameters:
      - description: 分页获取用户列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/modelinterface.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 根据id获取api
      tags:
      - API
  /api/getApiList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 分页获取API列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/modelinterface.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 分页获取API列表
      tags:
      - API
  /api/setAuthAndApi:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建api和角色关系
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.AuthAndPathIn'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 创建api和角色关系
      tags:
      - API
  /api/updataApi:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建api
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.CreateAPIParams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 创建基础api
      tags:
      - API
  /authority/createAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建角色
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.CreateAuthorityPatams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 创建角色
      tags:
      - authority
  /authority/deleteAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除角色
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.DeleteAuthorityPatams'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - authority
  /authority/getAuthAndAPI:
    post:
      consumes:
      - application/json
      parameters:
      - description: 获取本角色所有有权限的apiId
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.GetAuthorityID'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 获取本角色所有有权限的apiId
      tags:
      - authority
  /authority/getAuthorityList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 分页获取用户列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/modelinterface.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 分页获取角色列表
      tags:
      - authority
  /base/login:
    post:
      parameters:
      - description: 用户登录接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegistAndLoginStuct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            $ref: '#/definitions/api.response'
      summary: 用户登录
      tags:
      - Base
  /base/regist:
    post:
      parameters:
      - description: 用户注册接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegistAndLoginStuct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            $ref: '#/definitions/api.response'
      summary: 用户注册账号
      tags:
      - Base
  /menu/addBaseMenu:
    post:
      consumes:
      - application/json
      parameters:
      - description: 新增菜单
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.BaseMenu'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 新增菜单
      tags:
      - menu
  /menu/addMenuAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: 增加menu和角色关联关系
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.AuthorityIDInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 获取指定角色menu
      tags:
      - authorityAndMenu
  /menu/deleteBaseMenu:
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除菜单
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.IDInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 删除菜单
      tags:
      - menu
  /menu/getBaseMenuById:
    post:
      consumes:
      - application/json
      parameters:
      - description: 根据id获取菜单
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.GetByID'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 根据id获取菜单
      tags:
      - menu
  /menu/getBaseMenuTree:
    post:
      parameters:
      - description: 可以什么都不填
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegistAndLoginStuct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"返回成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户动态路由
      tags:
      - authorityAndMenu
  /menu/getMenu:
    post:
      parameters:
      - description: 可以什么都不填
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegistAndLoginStuct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"返回成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户动态路由
      tags:
      - authorityAndMenu
  /menu/getMenuList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 分页获取基础menu列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/modelinterface.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 分页获取基础menu列表
      tags:
      - menu
  /menu/updataBaseMen:
    post:
      consumes:
      - application/json
      parameters:
      - description: 更新菜单
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.BaseMenu'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 更新菜单
      tags:
      - menu
  /user/changePassword:
    post:
      parameters:
      - description: 用户修改密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.ChangePasswordStruct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"修改成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 用户修改密码
      tags:
      - User
  /user/getUserList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 分页获取用户列表
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/modelinterface.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"获取成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - User
  /user/setUserAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: 设置用户权限
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.SetUserAuth'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"修改成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 设置用户权限
      tags:
      - User
  /user/uploadHeaderImg:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 用户上传头像
        in: formData
        name: headerImg
        required: true
        type: file
      - description: 用户上传头像
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            $ref: '#/definitions/api.response'
      security:
      - ApiKeyAuth: []
      summary: 用户上传头像
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
